# Generated by Django 4.2.2 on 2023-07-18 07:24

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_ticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="نام و نام خانوادگی"),
                ),
                ("body", models.TextField(verbose_name="متن کامنت")),
                ("created", django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ("updated", django_jalali.db.models.jDateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=False, verbose_name="وضعیت")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment",
                        to="blog.post",
                        verbose_name="پست",
                    ),
                ),
            ],
            options={
                "verbose_name": "کامنت",
                "verbose_name_plural": "کامنت ها",
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="blog_commen_created_79f39f_idx"
                    )
                ],
            },
        ),
    ]
