# Generated by Django 4.2.2 on 2023-07-18 07:53

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created"],
                "verbose_name": "کامنت",
                "verbose_name_plural": "کامنت ها",
            },
        ),
        migrations.RemoveIndex(
            model_name="comment",
            name="blog_commen_created_79f39f_idx",
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=django_jalali.db.models.jDateTimeField(
                auto_now_add=True, verbose_name="تاریخ ایجاد"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="updated",
            field=django_jalali.db.models.jDateTimeField(
                auto_now=True, verbose_name="تاریخ ویرایش"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["created"], name="blog_commen_created_0e6ed4_idx"
            ),
        ),
    ]
