# Generated by Django 4.2.2 on 2023-07-31 16:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_file",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                force_format=None,
                keep_meta=True,
                quality=75,
                scale=None,
                size=[500, 500],
                upload_to="post_image/",
            ),
        ),
    ]
