# Generated by Django 4.2.2 on 2023-08-10 07:39

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0019_alter_account_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="بایو"),
        ),
        migrations.AlterField(
            model_name="account",
            name="job",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="شغل"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="photo",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                force_format=None,
                keep_meta=True,
                null=True,
                quality=60,
                scale=None,
                size=[500, 500],
                upload_to="account_image/",
                verbose_name="تصویر پروفایل",
            ),
        ),
    ]
