# Generated by Django 4.2.2 on 2023-08-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0020_alter_account_bio_alter_account_job_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("تکنولوژی", "تکنولوژی"),
                    ("برنامه نویسی", "برنامه نویسی"),
                    ("هوش مصنوعی", "هوش مصنوعی"),
                    ("سایر", "سایر"),
                ],
                default="سایر",
                max_length=20,
                verbose_name="دسته بندی",
            ),
        ),
    ]
